sequenceDiagram
    participant browser
    participant server

    browser->>browser: The browser render the new information of the new_note and then Send the new note to que server

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    

   